#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Backroom警报声_BP

#include "Basic.hpp"

#include "Backroom警报声_BP_classes.hpp"
#include "Backroom警报声_BP_parameters.hpp"


namespace SDK
{

// Function Backroom警报声_BP.Backroom警报声_BP_C.ExecuteUbergraph_Backroom警报声_BP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABackroom警报声_BP_C::ExecuteUbergraph_Backroom警报声_BP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Backroom警报声_BP_C", "ExecuteUbergraph_Backroom警报声_BP");

	Params::Backroom警报声_BP_C_ExecuteUbergraph_Backroom警报声_BP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Backroom警报声_BP.Backroom警报声_BP_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABackroom警报声_BP_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Backroom警报声_BP_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Backroom警报声_BP.Backroom警报声_BP_C.时间轴_0__UpdateFunc
// (BlueprintEvent)

void ABackroom警报声_BP_C::时间轴_0__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Backroom警报声_BP_C", "时间轴_0__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Backroom警报声_BP.Backroom警报声_BP_C.时间轴_0__FinishedFunc
// (BlueprintEvent)

void ABackroom警报声_BP_C::时间轴_0__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Backroom警报声_BP_C", "时间轴_0__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}

}

