#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Backroom_AK74_BP

#include "Basic.hpp"

#include "Backroom_AK74_BP_classes.hpp"
#include "Backroom_AK74_BP_parameters.hpp"


namespace SDK
{

// Function Backroom_AK74_BP.Backroom_AK74_BP_C.ExecuteUbergraph_Backroom_AK74_BP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABackroom_AK74_BP_C::ExecuteUbergraph_Backroom_AK74_BP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Backroom_AK74_BP_C", "ExecuteUbergraph_Backroom_AK74_BP");

	Params::Backroom_AK74_BP_C_ExecuteUbergraph_Backroom_AK74_BP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Backroom_AK74_BP.Backroom_AK74_BP_C.开始换弹
// (BlueprintCallable, BlueprintEvent)

void ABackroom_AK74_BP_C::开始换弹()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Backroom_AK74_BP_C", "开始换弹");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Backroom_AK74_BP.Backroom_AK74_BP_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABackroom_AK74_BP_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Backroom_AK74_BP_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Backroom_AK74_BP.Backroom_AK74_BP_C.武器子弹空仓动画
// (BlueprintCallable, BlueprintEvent)

void ABackroom_AK74_BP_C::武器子弹空仓动画()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Backroom_AK74_BP_C", "武器子弹空仓动画");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Backroom_AK74_BP.Backroom_AK74_BP_C.播放射击
// (BlueprintCallable, BlueprintEvent)

void ABackroom_AK74_BP_C::播放射击()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Backroom_AK74_BP_C", "播放射击");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Backroom_AK74_BP.Backroom_AK74_BP_C.是否是空仓状态
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    空仓换弹(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABackroom_AK74_BP_C::是否是空仓状态(bool 空仓换弹)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Backroom_AK74_BP_C", "是否是空仓状态");

	Params::Backroom_AK74_BP_C_是否是空仓状态 Parms{};

	Parms.空仓换弹 = 空仓换弹;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Backroom_AK74_BP.Backroom_AK74_BP_C.停止蒙太奇
// (Public, BlueprintCallable, BlueprintEvent)

void ABackroom_AK74_BP_C::停止蒙太奇()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Backroom_AK74_BP_C", "停止蒙太奇");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Backroom_AK74_BP.Backroom_AK74_BP_C.CheckMagazine
// (Public, BlueprintCallable, BlueprintEvent)

void ABackroom_AK74_BP_C::CheckMagazine()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Backroom_AK74_BP_C", "CheckMagazine");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Backroom_AK74_BP.Backroom_AK74_BP_C.CheckChamber
// (Public, BlueprintCallable, BlueprintEvent)

void ABackroom_AK74_BP_C::CheckChamber()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Backroom_AK74_BP_C", "CheckChamber");

	UObject::ProcessEvent(Func, nullptr);
}

}

