#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LockComponent

#include "Basic.hpp"

#include "BP_LockComponent_classes.hpp"
#include "BP_LockComponent_parameters.hpp"


namespace SDK
{

// Function BP_LockComponent.BP_LockComponent_C.ExecuteUbergraph_BP_LockComponent
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_LockComponent_C::ExecuteUbergraph_BP_LockComponent(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LockComponent_C", "ExecuteUbergraph_BP_LockComponent");

	Params::BP_LockComponent_C_ExecuteUbergraph_BP_LockComponent Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_LockComponent.BP_LockComponent_C.SetHUDInfo
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUI_LockpickingHUD_C*             HUD                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_LockComponent_C::SetHUDInfo(class UUI_LockpickingHUD_C* HUD)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LockComponent_C", "SetHUDInfo");

	Params::BP_LockComponent_C_SetHUDInfo Parms{};

	Parms.HUD = HUD;

	UObject::ProcessEvent(Func, &Parms);
}

}

