#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_角色模型捕捉

#include "Basic.hpp"

#include "BP_角色模型捕捉_classes.hpp"
#include "BP_角色模型捕捉_parameters.hpp"


namespace SDK
{

// Function BP_角色模型捕捉.BP_角色模型捕捉_C.ExecuteUbergraph_BP_角色模型捕捉
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_角色模型捕捉_C::ExecuteUbergraph_BP_角色模型捕捉(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_角色模型捕捉_C", "ExecuteUbergraph_BP_角色模型捕捉");

	Params::BP_角色模型捕捉_C_ExecuteUbergraph_BP_角色模型捕捉 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_角色模型捕捉.BP_角色模型捕捉_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_角色模型捕捉_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_角色模型捕捉_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_角色模型捕捉.BP_角色模型捕捉_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_角色模型捕捉_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_角色模型捕捉_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_角色模型捕捉.BP_角色模型捕捉_C.应用读取的数据
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_角色模型捕捉_C::应用读取的数据()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_角色模型捕捉_C", "应用读取的数据");

	UObject::ProcessEvent(Func, nullptr);
}

}

