#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CustomButton_UMG4

#include "Basic.hpp"

#include "CustomButton_UMG4_classes.hpp"
#include "CustomButton_UMG4_parameters.hpp"


namespace SDK
{

// Function CustomButton_UMG4.CustomButton_UMG4_C.ExecuteUbergraph_CustomButton_UMG4
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCustomButton_UMG4_C::ExecuteUbergraph_CustomButton_UMG4(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomButton_UMG4_C", "ExecuteUbergraph_CustomButton_UMG4");

	Params::CustomButton_UMG4_C_ExecuteUbergraph_CustomButton_UMG4 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CustomButton_UMG4.CustomButton_UMG4_C.BndEvt__CustomButton_UMG_Button_131_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UCustomButton_UMG4_C::BndEvt__CustomButton_UMG_Button_131_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomButton_UMG4_C", "BndEvt__CustomButton_UMG_Button_131_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CustomButton_UMG4.CustomButton_UMG4_C.BndEvt__Button_131_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UCustomButton_UMG4_C::BndEvt__Button_131_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomButton_UMG4_C", "BndEvt__Button_131_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CustomButton_UMG4.CustomButton_UMG4_C.BndEvt__Button_131_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UCustomButton_UMG4_C::BndEvt__Button_131_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomButton_UMG4_C", "BndEvt__Button_131_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CustomButton_UMG4.CustomButton_UMG4_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UCustomButton_UMG4_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomButton_UMG4_C", "PreConstruct");

	Params::CustomButton_UMG4_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

