#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CustomCharacter

#include "Basic.hpp"

#include "CustomCharacter_classes.hpp"
#include "CustomCharacter_parameters.hpp"


namespace SDK
{

// Function CustomCharacter.CustomCharacter_C.ExecuteUbergraph_CustomCharacter
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ACustomCharacter_C::ExecuteUbergraph_CustomCharacter(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomCharacter_C", "ExecuteUbergraph_CustomCharacter");

	Params::CustomCharacter_C_ExecuteUbergraph_CustomCharacter Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CustomCharacter.CustomCharacter_C.恢复默认设置
// (BlueprintCallable, BlueprintEvent)

void ACustomCharacter_C::恢复默认设置()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomCharacter_C", "恢复默认设置");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CustomCharacter.CustomCharacter_C.播放微笑动画
// (BlueprintCallable, BlueprintEvent)

void ACustomCharacter_C::播放微笑动画()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomCharacter_C", "播放微笑动画");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CustomCharacter.CustomCharacter_C.播放眨眼动画
// (BlueprintCallable, BlueprintEvent)

void ACustomCharacter_C::播放眨眼动画()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomCharacter_C", "播放眨眼动画");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CustomCharacter.CustomCharacter_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ACustomCharacter_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomCharacter_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CustomCharacter.CustomCharacter_C.InpAxisEvt_Turn_K2Node_InputAxisEvent_0
// (BlueprintEvent)
// Parameters:
// float                                   AxisValue                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ACustomCharacter_C::InpAxisEvt_Turn_K2Node_InputAxisEvent_0(float AxisValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomCharacter_C", "InpAxisEvt_Turn_K2Node_InputAxisEvent_0");

	Params::CustomCharacter_C_InpAxisEvt_Turn_K2Node_InputAxisEvent_0 Parms{};

	Parms.AxisValue = AxisValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CustomCharacter.CustomCharacter_C.随机跳舞
// (BlueprintCallable, BlueprintEvent)

void ACustomCharacter_C::随机跳舞()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomCharacter_C", "随机跳舞");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CustomCharacter.CustomCharacter_C.选择人物_Event
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// ECharacterModel                         Selection                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ACustomCharacter_C::选择人物_Event(ECharacterModel Selection)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomCharacter_C", "选择人物_Event");

	Params::CustomCharacter_C_选择人物_Event Parms{};

	Parms.Selection = Selection;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CustomCharacter.CustomCharacter_C.InpActEvt_LeftMouseButton_K2Node_InputKeyEvent_0
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void ACustomCharacter_C::InpActEvt_LeftMouseButton_K2Node_InputKeyEvent_0(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomCharacter_C", "InpActEvt_LeftMouseButton_K2Node_InputKeyEvent_0");

	Params::CustomCharacter_C_InpActEvt_LeftMouseButton_K2Node_InputKeyEvent_0 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function CustomCharacter.CustomCharacter_C.InpActEvt_LeftMouseButton_K2Node_InputKeyEvent_1
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void ACustomCharacter_C::InpActEvt_LeftMouseButton_K2Node_InputKeyEvent_1(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomCharacter_C", "InpActEvt_LeftMouseButton_K2Node_InputKeyEvent_1");

	Params::CustomCharacter_C_InpActEvt_LeftMouseButton_K2Node_InputKeyEvent_1 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function CustomCharacter.CustomCharacter_C.OnCompleted_9662C3F24F401F50D7E320ABFEEF79EA
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ACustomCharacter_C::OnCompleted_9662C3F24F401F50D7E320ABFEEF79EA(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomCharacter_C", "OnCompleted_9662C3F24F401F50D7E320ABFEEF79EA");

	Params::CustomCharacter_C_OnCompleted_9662C3F24F401F50D7E320ABFEEF79EA Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CustomCharacter.CustomCharacter_C.OnBlendOut_9662C3F24F401F50D7E320ABFEEF79EA
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ACustomCharacter_C::OnBlendOut_9662C3F24F401F50D7E320ABFEEF79EA(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomCharacter_C", "OnBlendOut_9662C3F24F401F50D7E320ABFEEF79EA");

	Params::CustomCharacter_C_OnBlendOut_9662C3F24F401F50D7E320ABFEEF79EA Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CustomCharacter.CustomCharacter_C.OnInterrupted_9662C3F24F401F50D7E320ABFEEF79EA
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ACustomCharacter_C::OnInterrupted_9662C3F24F401F50D7E320ABFEEF79EA(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomCharacter_C", "OnInterrupted_9662C3F24F401F50D7E320ABFEEF79EA");

	Params::CustomCharacter_C_OnInterrupted_9662C3F24F401F50D7E320ABFEEF79EA Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CustomCharacter.CustomCharacter_C.OnNotifyBegin_9662C3F24F401F50D7E320ABFEEF79EA
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ACustomCharacter_C::OnNotifyBegin_9662C3F24F401F50D7E320ABFEEF79EA(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomCharacter_C", "OnNotifyBegin_9662C3F24F401F50D7E320ABFEEF79EA");

	Params::CustomCharacter_C_OnNotifyBegin_9662C3F24F401F50D7E320ABFEEF79EA Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CustomCharacter.CustomCharacter_C.OnNotifyEnd_9662C3F24F401F50D7E320ABFEEF79EA
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ACustomCharacter_C::OnNotifyEnd_9662C3F24F401F50D7E320ABFEEF79EA(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomCharacter_C", "OnNotifyEnd_9662C3F24F401F50D7E320ABFEEF79EA");

	Params::CustomCharacter_C_OnNotifyEnd_9662C3F24F401F50D7E320ABFEEF79EA Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CustomCharacter.CustomCharacter_C.时间轴_1__UpdateFunc
// (BlueprintEvent)

void ACustomCharacter_C::时间轴_1__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomCharacter_C", "时间轴_1__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CustomCharacter.CustomCharacter_C.时间轴_1__FinishedFunc
// (BlueprintEvent)

void ACustomCharacter_C::时间轴_1__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomCharacter_C", "时间轴_1__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CustomCharacter.CustomCharacter_C.时间轴_0__UpdateFunc
// (BlueprintEvent)

void ACustomCharacter_C::时间轴_0__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomCharacter_C", "时间轴_0__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CustomCharacter.CustomCharacter_C.时间轴_0__FinishedFunc
// (BlueprintEvent)

void ACustomCharacter_C::时间轴_0__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomCharacter_C", "时间轴_0__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CustomCharacter.CustomCharacter_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ACustomCharacter_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomCharacter_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CustomCharacter.CustomCharacter_C.拖动旋转
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Z                                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ACustomCharacter_C::拖动旋转(float Z)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomCharacter_C", "拖动旋转");

	Params::CustomCharacter_C_拖动旋转 Parms{};

	Parms.Z = Z;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CustomCharacter.CustomCharacter_C.应用读取的数据
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ACustomCharacter_C::应用读取的数据()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomCharacter_C", "应用读取的数据");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CustomCharacter.CustomCharacter_C.选择Man角色
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ACustomCharacter_C::选择Man角色()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomCharacter_C", "选择Man角色");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CustomCharacter.CustomCharacter_C.选择Female角色
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ACustomCharacter_C::选择Female角色()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomCharacter_C", "选择Female角色");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CustomCharacter.CustomCharacter_C.保存玩家选择信息
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// ECharacterModel                         CharacterModel_0                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ACustomCharacter_C::保存玩家选择信息(ECharacterModel CharacterModel_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomCharacter_C", "保存玩家选择信息");

	Params::CustomCharacter_C_保存玩家选择信息 Parms{};

	Parms.CharacterModel_0 = CharacterModel_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CustomCharacter.CustomCharacter_C.选择BunnyGirl角色
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ACustomCharacter_C::选择BunnyGirl角色()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomCharacter_C", "选择BunnyGirl角色");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CustomCharacter.CustomCharacter_C.选择Amaya角色
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ACustomCharacter_C::选择Amaya角色()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomCharacter_C", "选择Amaya角色");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CustomCharacter.CustomCharacter_C.选择Maid角色
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ACustomCharacter_C::选择Maid角色()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomCharacter_C", "选择Maid角色");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CustomCharacter.CustomCharacter_C.选择NewYearGirl角色
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ACustomCharacter_C::选择NewYearGirl角色()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomCharacter_C", "选择NewYearGirl角色");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CustomCharacter.CustomCharacter_C.选择SchoolGirl角色
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ACustomCharacter_C::选择SchoolGirl角色()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomCharacter_C", "选择SchoolGirl角色");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CustomCharacter.CustomCharacter_C.选择LadyBiker角色
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ACustomCharacter_C::选择LadyBiker角色()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomCharacter_C", "选择LadyBiker角色");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CustomCharacter.CustomCharacter_C.选择Soldier角色
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ACustomCharacter_C::选择Soldier角色()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomCharacter_C", "选择Soldier角色");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CustomCharacter.CustomCharacter_C.选择JuaLee角色
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ACustomCharacter_C::选择JuaLee角色()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomCharacter_C", "选择JuaLee角色");

	UObject::ProcessEvent(Func, nullptr);
}

}

