#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DirectLinkTest

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// Class DirectLinkTest.DirectLinkTestLibrary
// 0x0000 (0x0028 - 0x0028)
class UDirectLinkTestLibrary final : public UBlueprintFunctionLibrary
{
public:
	static bool AddPublicDestination(int32 EndpointId, const class FString& DestName);
	static bool AddPublicSource(int32 EndpointId, const class FString& SourceName);
	static bool DeleteAllEndpoint();
	static bool DeleteEndpoint(int32 EndpointId);
	static bool DumpReceivedScene();
	static int32 MakeEndpoint(const class FString& NiceName, bool bVerbose);
	static bool SendScene(const class FString& InFilePath);
	static bool SetupReceiver();
	static bool SetupSender();
	static bool StartReceiver();
	static bool StartSender();
	static bool StopReceiver();
	static bool StopSender();
	static bool TestParameters();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"DirectLinkTestLibrary">();
	}
	static class UDirectLinkTestLibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDirectLinkTestLibrary>();
	}
};
static_assert(alignof(UDirectLinkTestLibrary) == 0x000008, "Wrong alignment on UDirectLinkTestLibrary");
static_assert(sizeof(UDirectLinkTestLibrary) == 0x000028, "Wrong size on UDirectLinkTestLibrary");

}

