#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FindPlayer

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AIModule_structs.hpp"
#include "AIModule_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass FindPlayer.FindPlayer_C
// 0x0008 (0x00B0 - 0x00A8)
class UFindPlayer_C final : public UBTTask_BlueprintBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00A8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_FindPlayer(int32 EntryPoint);
	void ReceiveTickAI(class AAIController* OwnerController, class APawn* ControlledPawn, float DeltaSeconds);
	void OnSuccess_046049DF483FCA9EB69F85BA3AE72C88(EPathFollowingResult MovementResult);
	void OnFail_046049DF483FCA9EB69F85BA3AE72C88(EPathFollowingResult MovementResult);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"FindPlayer_C">();
	}
	static class UFindPlayer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFindPlayer_C>();
	}
};
static_assert(alignof(UFindPlayer_C) == 0x000008, "Wrong alignment on UFindPlayer_C");
static_assert(sizeof(UFindPlayer_C) == 0x0000B0, "Wrong size on UFindPlayer_C");
static_assert(offsetof(UFindPlayer_C, UberGraphFrame) == 0x0000A8, "Member 'UFindPlayer_C::UberGraphFrame' has a wrong offset!");

}

