#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Hit_CameraShake1

#include "Basic.hpp"

#include "GameplayCameras_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Hit_CameraShake1.Hit_CameraShake1_C
// 0x0000 (0x01B0 - 0x01B0)
class UHit_CameraShake1_C final : public UMatineeCameraShake
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Hit_CameraShake1_C">();
	}
	static class UHit_CameraShake1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UHit_CameraShake1_C>();
	}
};
static_assert(alignof(UHit_CameraShake1_C) == 0x000010, "Wrong alignment on UHit_CameraShake1_C");
static_assert(sizeof(UHit_CameraShake1_C) == 0x0001B0, "Wrong size on UHit_CameraShake1_C");

}

