#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: M416_BP

#include "Basic.hpp"

#include "Weapon_Master_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass M416_BP.M416_BP_C
// 0x0008 (0x0488 - 0x0480)
class AM416_BP_C final : public AWeapon_Master_C
{
public:
	class USkeletalMeshComponent*                 HK416_Stock_setting;                               // 0x0480(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"M416_BP_C">();
	}
	static class AM416_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AM416_BP_C>();
	}
};
static_assert(alignof(AM416_BP_C) == 0x000008, "Wrong alignment on AM416_BP_C");
static_assert(sizeof(AM416_BP_C) == 0x000488, "Wrong size on AM416_BP_C");
static_assert(offsetof(AM416_BP_C, HK416_Stock_setting) == 0x000480, "Member 'AM416_BP_C::HK416_Stock_setting' has a wrong offset!");

}

