#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MainMenuPlayerController

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass MainMenuPlayerController.MainMenuPlayerController_C
// 0x0010 (0x0580 - 0x0570)
class AMainMenuPlayerController_C final : public APlayerController
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0570(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UMainMenu_UMG_C*                        MainMenu_UMG;                                      // 0x0578(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void InpActEvt_Escape_K2Node_InputKeyEvent_0(const struct FKey& Key);
	void ReceiveBeginPlay();
	void ExecuteUbergraph_MainMenuPlayerController(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MainMenuPlayerController_C">();
	}
	static class AMainMenuPlayerController_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMainMenuPlayerController_C>();
	}
};
static_assert(alignof(AMainMenuPlayerController_C) == 0x000008, "Wrong alignment on AMainMenuPlayerController_C");
static_assert(sizeof(AMainMenuPlayerController_C) == 0x000580, "Wrong size on AMainMenuPlayerController_C");
static_assert(offsetof(AMainMenuPlayerController_C, UberGraphFrame) == 0x000570, "Member 'AMainMenuPlayerController_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(AMainMenuPlayerController_C, MainMenu_UMG) == 0x000578, "Member 'AMainMenuPlayerController_C::MainMenu_UMG' has a wrong offset!");

}

