#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MapType

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum MapType.MapType
// NumValues: 0x0005
enum class EMapType : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator3                           = 2,
	NewEnumerator4                           = 3,
	MapType_MAX                              = 4,
};

}

