#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Nine_19Ammo_BP

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "PickUpMaster_BP_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass 9_19Ammo_BP.9_19Ammo_BP_C
// 0x0008 (0x0330 - 0x0328)
class ANine_19Ammo_BP_C final : public APickUpMaster_BP_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_Nine_19Ammo_BP_C;                   // 0x0328(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_9_19Ammo_BP(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"9_19Ammo_BP_C">();
	}
	static class ANine_19Ammo_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ANine_19Ammo_BP_C>();
	}
};
static_assert(alignof(ANine_19Ammo_BP_C) == 0x000008, "Wrong alignment on ANine_19Ammo_BP_C");
static_assert(sizeof(ANine_19Ammo_BP_C) == 0x000330, "Wrong size on ANine_19Ammo_BP_C");
static_assert(offsetof(ANine_19Ammo_BP_C, UberGraphFrame_Nine_19Ammo_BP_C) == 0x000328, "Member 'ANine_19Ammo_BP_C::UberGraphFrame_Nine_19Ammo_BP_C' has a wrong offset!");

}

