#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PlayerInteration

#include "Basic.hpp"


namespace SDK::Params
{

// Function PlayerInteration.PlayerInteration_C.PlayerInteration
// 0x0008 (0x0008 - 0x0000)
struct PlayerInteration_C_PlayerInteration final
{
public:
	class AActor*                                 Player;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PlayerInteration_C_PlayerInteration) == 0x000008, "Wrong alignment on PlayerInteration_C_PlayerInteration");
static_assert(sizeof(PlayerInteration_C_PlayerInteration) == 0x000008, "Wrong size on PlayerInteration_C_PlayerInteration");
static_assert(offsetof(PlayerInteration_C_PlayerInteration, Player) == 0x000000, "Member 'PlayerInteration_C_PlayerInteration::Player' has a wrong offset!");

}

