#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PlotClue_Blueprint

#include "Basic.hpp"

#include "PlotClue_Blueprint_classes.hpp"
#include "PlotClue_Blueprint_parameters.hpp"


namespace SDK
{

// Function PlotClue_Blueprint.PlotClue_Blueprint_C.ExecuteUbergraph_PlotClue_Blueprint
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APlotClue_Blueprint_C::ExecuteUbergraph_PlotClue_Blueprint(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlotClue_Blueprint_C", "ExecuteUbergraph_PlotClue_Blueprint");

	Params::PlotClue_Blueprint_C_ExecuteUbergraph_PlotClue_Blueprint Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PlotClue_Blueprint.PlotClue_Blueprint_C.BndEvt__BP_cp02_Sphere1_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              OverlappedComponent                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   OtherBodyIndex                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APlotClue_Blueprint_C::BndEvt__BP_cp02_Sphere1_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlotClue_Blueprint_C", "BndEvt__BP_cp02_Sphere1_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature");

	Params::PlotClue_Blueprint_C_BndEvt__BP_cp02_Sphere1_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature Parms{};

	Parms.OverlappedComponent = OverlappedComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.OtherBodyIndex = OtherBodyIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PlotClue_Blueprint.PlotClue_Blueprint_C.BndEvt__BP_cp02_Sphere1_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              OverlappedComponent                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   OtherBodyIndex                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bFromSweep                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// const struct FHitResult&                SweepResult                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void APlotClue_Blueprint_C::BndEvt__BP_cp02_Sphere1_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlotClue_Blueprint_C", "BndEvt__BP_cp02_Sphere1_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature");

	Params::PlotClue_Blueprint_C_BndEvt__BP_cp02_Sphere1_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature Parms{};

	Parms.OverlappedComponent = OverlappedComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.OtherBodyIndex = OtherBodyIndex;
	Parms.bFromSweep = bFromSweep;
	Parms.SweepResult = std::move(SweepResult);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PlotClue_Blueprint.PlotClue_Blueprint_C.手电筒开关
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ON                                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void APlotClue_Blueprint_C::手电筒开关(bool ON)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlotClue_Blueprint_C", "手电筒开关");

	Params::PlotClue_Blueprint_C_手电筒开关 Parms{};

	Parms.ON = ON;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PlotClue_Blueprint.PlotClue_Blueprint_C.BreakInteration
// (Public, BlueprintCallable, BlueprintEvent)

void APlotClue_Blueprint_C::BreakInteration()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlotClue_Blueprint_C", "BreakInteration");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PlotClue_Blueprint.PlotClue_Blueprint_C.RenderDeepClose
// (Public, BlueprintCallable, BlueprintEvent)

void APlotClue_Blueprint_C::RenderDeepClose()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlotClue_Blueprint_C", "RenderDeepClose");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PlotClue_Blueprint.PlotClue_Blueprint_C.RenderDeepOpen
// (Public, BlueprintCallable, BlueprintEvent)

void APlotClue_Blueprint_C::RenderDeepOpen()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlotClue_Blueprint_C", "RenderDeepOpen");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PlotClue_Blueprint.PlotClue_Blueprint_C.PlayerInteration
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Player_0                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APlotClue_Blueprint_C::PlayerInteration(class AActor* Player_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlotClue_Blueprint_C", "PlayerInteration");

	Params::PlotClue_Blueprint_C_PlayerInteration Parms{};

	Parms.Player_0 = Player_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PlotClue_Blueprint.PlotClue_Blueprint_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void APlotClue_Blueprint_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlotClue_Blueprint_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PlotClue_Blueprint.PlotClue_Blueprint_C.InpActEvt_PlayerInteration_K2Node_InputActionEvent_0
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void APlotClue_Blueprint_C::InpActEvt_PlayerInteration_K2Node_InputActionEvent_0(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlotClue_Blueprint_C", "InpActEvt_PlayerInteration_K2Node_InputActionEvent_0");

	Params::PlotClue_Blueprint_C_InpActEvt_PlayerInteration_K2Node_InputActionEvent_0 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}

}

