#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: QteFail

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass QteFail.QteFail_C
// 0x0008 (0x0040 - 0x0038)
class UQteFail_C final : public UAnimNotify
{
public:
	float                                         Scale;                                             // 0x0038(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	bool Received_Notify(class USkeletalMeshComponent* MeshComp, class UAnimSequenceBase* Animation) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"QteFail_C">();
	}
	static class UQteFail_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UQteFail_C>();
	}
};
static_assert(alignof(UQteFail_C) == 0x000008, "Wrong alignment on UQteFail_C");
static_assert(sizeof(UQteFail_C) == 0x000040, "Wrong size on UQteFail_C");
static_assert(offsetof(UQteFail_C, Scale) == 0x000038, "Member 'UQteFail_C::Scale' has a wrong offset!");

}

