#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: QuestTipUI_BP

#include "Basic.hpp"

#include "QuestTipUI_BP_classes.hpp"
#include "QuestTipUI_BP_parameters.hpp"


namespace SDK
{

// Function QuestTipUI_BP.QuestTipUI_BP_C.ExecuteUbergraph_QuestTipUI_BP
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AQuestTipUI_BP_C::ExecuteUbergraph_QuestTipUI_BP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("QuestTipUI_BP_C", "ExecuteUbergraph_QuestTipUI_BP");

	Params::QuestTipUI_BP_C_ExecuteUbergraph_QuestTipUI_BP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function QuestTipUI_BP.QuestTipUI_BP_C.完成计数任务
// (BlueprintCallable, BlueprintEvent)

void AQuestTipUI_BP_C::完成计数任务()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("QuestTipUI_BP_C", "完成计数任务");

	UObject::ProcessEvent(Func, nullptr);
}


// Function QuestTipUI_BP.QuestTipUI_BP_C.初始化计数任务
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   总共要完成几个(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           QuestSystem_0                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AQuestTipUI_BP_C::初始化计数任务(int32 总共要完成几个, class AActor* QuestSystem_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("QuestTipUI_BP_C", "初始化计数任务");

	Params::QuestTipUI_BP_C_初始化计数任务 Parms{};

	Parms.总共要完成几个 = 总共要完成几个;
	Parms.QuestSystem_0 = QuestSystem_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function QuestTipUI_BP.QuestTipUI_BP_C.刷新任务系统
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      InText                                                 (BlueprintVisible, BlueprintReadOnly, Parm)
// class UTexture2D*                       Texture                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AQuestTipUI_BP_C::刷新任务系统(const class FText& InText, class UTexture2D* Texture)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("QuestTipUI_BP_C", "刷新任务系统");

	Params::QuestTipUI_BP_C_刷新任务系统 Parms{};

	Parms.InText = std::move(InText);
	Parms.Texture = Texture;

	UObject::ProcessEvent(Func, &Parms);
}

}

