#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UIWeapon

#include "Basic.hpp"

#include "UIWeapon_classes.hpp"


namespace SDK
{

// Function UIWeapon.UIWeapon_C.关闭所有武器选择
// (Public, BlueprintCallable, BlueprintEvent)

void IUIWeapon_C::关闭所有武器选择()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("UIWeapon_C", "关闭所有武器选择");

	AsUObject()->ProcessEvent(Func, nullptr);
}


// Function UIWeapon.UIWeapon_C.关闭所有配件种类选择
// (Public, BlueprintCallable, BlueprintEvent)

void IUIWeapon_C::关闭所有配件种类选择()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("UIWeapon_C", "关闭所有配件种类选择");

	AsUObject()->ProcessEvent(Func, nullptr);
}


// Function UIWeapon.UIWeapon_C.关闭所有配件详情选择
// (Public, BlueprintCallable, BlueprintEvent)

void IUIWeapon_C::关闭所有配件详情选择()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("UIWeapon_C", "关闭所有配件详情选择");

	AsUObject()->ProcessEvent(Func, nullptr);
}

}

