#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VagrantBullet_BP

#include "Basic.hpp"

#include "BulletMaster_BP_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass VagrantBullet_BP.VagrantBullet_BP_C
// 0x0000 (0x0248 - 0x0248)
class AVagrantBullet_BP_C final : public ABulletMaster_BP_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"VagrantBullet_BP_C">();
	}
	static class AVagrantBullet_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AVagrantBullet_BP_C>();
	}
};
static_assert(alignof(AVagrantBullet_BP_C) == 0x000008, "Wrong alignment on AVagrantBullet_BP_C");
static_assert(sizeof(AVagrantBullet_BP_C) == 0x000248, "Wrong size on AVagrantBullet_BP_C");

}

