#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: 主界面音效

#include "Basic.hpp"


namespace SDK::Params
{

// Function 主界面音效.主界面音效_C.ExecuteUbergraph_主界面音效
// 0x0010 (0x0010 - 0x0000)
struct 主界面音效_C_ExecuteUbergraph_主界面音效 final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class USoundBase*                             K2Node_CustomEvent_NewSound;                       // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(主界面音效_C_ExecuteUbergraph_主界面音效) == 0x000008, "Wrong alignment on 主界面音效_C_ExecuteUbergraph_主界面音效");
static_assert(sizeof(主界面音效_C_ExecuteUbergraph_主界面音效) == 0x000010, "Wrong size on 主界面音效_C_ExecuteUbergraph_主界面音效");
static_assert(offsetof(主界面音效_C_ExecuteUbergraph_主界面音效, EntryPoint) == 0x000000, "Member '主界面音效_C_ExecuteUbergraph_主界面音效::EntryPoint' has a wrong offset!");
static_assert(offsetof(主界面音效_C_ExecuteUbergraph_主界面音效, K2Node_CustomEvent_NewSound) == 0x000008, "Member '主界面音效_C_ExecuteUbergraph_主界面音效::K2Node_CustomEvent_NewSound' has a wrong offset!");

// Function 主界面音效.主界面音效_C.切换主菜单音效
// 0x0008 (0x0008 - 0x0000)
struct 主界面音效_C_切换主菜单音效 final
{
public:
	class USoundBase*                             NewSound;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(主界面音效_C_切换主菜单音效) == 0x000008, "Wrong alignment on 主界面音效_C_切换主菜单音效");
static_assert(sizeof(主界面音效_C_切换主菜单音效) == 0x000008, "Wrong size on 主界面音效_C_切换主菜单音效");
static_assert(offsetof(主界面音效_C_切换主菜单音效, NewSound) == 0x000000, "Member '主界面音效_C_切换主菜单音效::NewSound' has a wrong offset!");

}

